// Generated by scripts/generate-l2-abis.mjs from pinned OP artifacts.
// Do not edit manually; run npm run generate:l2-abis.

import type { Abi } from "viem";

export const opContractsBedrockArtifactSource = {
  packageName: "@eth-optimism/contracts-bedrock",
  version: "0.17.3",
  artifacts: [
    {
      "exportName": "l2StandardBridgeAbi",
      "source": "forge-artifacts/L2StandardBridge.sol/L2StandardBridge.json",
      "compiler": "0.8.15+commit.e14f2714"
    },
    {
      "exportName": "l2Erc721BridgeAbi",
      "source": "forge-artifacts/L2ERC721Bridge.sol/L2ERC721Bridge.json",
      "compiler": "0.8.15+commit.e14f2714"
    },
    {
      "exportName": "l2ToL1MessagePasserAbi",
      "source": "forge-artifacts/L2ToL1MessagePasser.sol/L2ToL1MessagePasser.json",
      "compiler": "0.8.15+commit.e14f2714"
    }
  ],
} as const;

export const l2StandardBridgeAbi = [
  {
    "type": "function",
    "name": "withdraw",
    "inputs": [
      {
        "name": "_l2Token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "_amount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "_minGasLimit",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "_extraData",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "withdrawTo",
    "inputs": [
      {
        "name": "_l2Token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "_to",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "_amount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "_minGasLimit",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "_extraData",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "payable"
  },
  {
    "type": "event",
    "name": "WithdrawalInitiated",
    "inputs": [
      {
        "name": "l1Token",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "l2Token",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "from",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "to",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "extraData",
        "type": "bytes",
        "indexed": false,
        "internalType": "bytes"
      }
    ],
    "anonymous": false
  }
] as const satisfies Abi;

export const l2Erc721BridgeAbi = [
  {
    "type": "function",
    "name": "bridgeERC721To",
    "inputs": [
      {
        "name": "_localToken",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "_remoteToken",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "_to",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "_tokenId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "_minGasLimit",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "_extraData",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  }
] as const satisfies Abi;

export const l2ToL1MessagePasserAbi = [
  {
    "type": "function",
    "name": "initiateWithdrawal",
    "inputs": [
      {
        "name": "_target",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "_gasLimit",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "_data",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "payable"
  },
  {
    "type": "event",
    "name": "MessagePassed",
    "inputs": [
      {
        "name": "nonce",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "sender",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "target",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "value",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "gasLimit",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "data",
        "type": "bytes",
        "indexed": false,
        "internalType": "bytes"
      },
      {
        "name": "withdrawalHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  }
] as const satisfies Abi;
