#!/usr/bin/env node

import { createRequire } from "node:module";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const require = createRequire(import.meta.url);
const artifactPackage = "@eth-optimism/contracts-bedrock";
const artifactPackageVersion = "0.17.3";
const artifactPackageJsonPath = require.resolve(`${artifactPackage}/package.json`);
const artifactRoot = path.dirname(artifactPackageJsonPath);

const artifacts = [
  {
    exportName: "l2StandardBridgeAbi",
    source: "forge-artifacts/L2StandardBridge.sol/L2StandardBridge.json",
    fragments: [
      {
        type: "function",
        name: "withdraw",
        inputs: ["address", "uint256", "uint32", "bytes"],
        stateMutability: "payable",
      },
      {
        type: "function",
        name: "withdrawTo",
        inputs: ["address", "address", "uint256", "uint32", "bytes"],
        stateMutability: "payable",
      },
      {
        type: "event",
        name: "WithdrawalInitiated",
        inputs: ["address", "address", "address", "address", "uint256", "bytes"],
        indexed: [true, true, true, false, false, false],
      },
    ],
  },
  {
    exportName: "l2Erc721BridgeAbi",
    source: "forge-artifacts/L2ERC721Bridge.sol/L2ERC721Bridge.json",
    fragments: [
      {
        type: "function",
        name: "bridgeERC721To",
        inputs: ["address", "address", "address", "uint256", "uint32", "bytes"],
        stateMutability: "nonpayable",
      },
    ],
  },
  {
    exportName: "l2ToL1MessagePasserAbi",
    source: "forge-artifacts/L2ToL1MessagePasser.sol/L2ToL1MessagePasser.json",
    fragments: [
      {
        type: "function",
        name: "initiateWithdrawal",
        inputs: ["address", "uint256", "bytes"],
        stateMutability: "payable",
      },
      {
        type: "event",
        name: "MessagePassed",
        inputs: ["uint256", "address", "address", "uint256", "uint256", "bytes", "bytes32"],
        indexed: [true, true, true, false, false, false, false],
      },
    ],
  },
];

const packageJson = JSON.parse(await readFile(artifactPackageJsonPath, "utf8"));
if (packageJson.version !== artifactPackageVersion) {
  throw new Error(
    `${artifactPackage} artifact version changed: expected ${artifactPackageVersion}, got ${packageJson.version}`
  );
}
const generated = [];

for (const artifact of artifacts) {
  const artifactPath = path.join(artifactRoot, artifact.source);
  const data = await readArtifact(artifact, artifactPath);
  if (!Array.isArray(data.abi)) {
    throw new Error(`${artifact.source} does not contain an ABI array`);
  }
  const compiler = data.metadata?.compiler?.version;
  if (typeof compiler !== "string" || compiler.length === 0) {
    throw new Error(`${artifact.source} does not contain a compiler version`);
  }
  const abi = artifact.fragments.map((fragment) => requireFragment(artifact, data.abi, fragment));
  generated.push({
    ...artifact,
    abi,
    compiler,
  });
}

const out = `// Generated by scripts/generate-l2-abis.mjs from pinned OP artifacts.
// Do not edit manually; run npm run generate:l2-abis.

import type { DuskEvmAbi } from "./types.js";

/** Provenance metadata for the pinned OP contracts package and selected artifacts. */
export const opContractsBedrockArtifactSource = {
  packageName: ${JSON.stringify(artifactPackage)},
  version: ${JSON.stringify(packageJson.version)},
  artifacts: ${formatJson(
    generated.map(({ exportName, source, compiler }) => ({
      exportName,
      source,
      compiler,
    })),
    2
  )},
} as const;

${generated
  .map(
    ({ exportName, abi }) =>
      `${abiDocumentation(exportName)}\nexport const ${exportName}: DuskEvmAbi = ${formatJson(abi)} as const satisfies DuskEvmAbi;`
  )
  .join("\n\n")}
`;

await writeFile(new URL("../src/l2/op-abis.ts", import.meta.url), out);

async function readArtifact(artifact, artifactPath) {
  try {
    return JSON.parse(await readFile(artifactPath, "utf8"));
  } catch (error) {
    throw new Error(
      `Unable to read ${artifactPackage}@${artifactPackageVersion} artifact ${artifact.source}`,
      { cause: error }
    );
  }
}

function requireFragment(artifact, abi, fragment) {
  const match = abi.find(
    (item) =>
      item.type === fragment.type &&
      item.name === fragment.name &&
      item.inputs.map((input) => input.type).join(",") === fragment.inputs.join(",")
  );
  if (!match) {
    throw new Error(
      `${artifact.source} is missing ${fragment.type} ${fragment.name}(${fragment.inputs.join(",")})`
    );
  }
  if (
    fragment.stateMutability !== undefined &&
    match.stateMutability !== fragment.stateMutability
  ) {
    throw new Error(
      `${artifact.source} ${fragment.name} has stateMutability ${match.stateMutability}, expected ${fragment.stateMutability}`
    );
  }
  if (
    fragment.indexed !== undefined &&
    match.inputs.map((input) => Boolean(input.indexed)).join(",") !== fragment.indexed.join(",")
  ) {
    throw new Error(
      `${artifact.source} ${fragment.name} indexed fields changed; expected ${fragment.indexed.join(",")}`
    );
  }
  return match;
}

function formatJson(value, continuationIndent = 0) {
  const raw = JSON.stringify(value, null, 2);
  if (continuationIndent === 0) return raw;
  return raw.replaceAll("\n", `\n${" ".repeat(continuationIndent)}`);
}

function abiDocumentation(exportName) {
  const descriptions = {
    l2StandardBridgeAbi: "Allowlisted OP L2 standard bridge ABI.",
    l2Erc721BridgeAbi: "Allowlisted OP L2 ERC721 bridge ABI.",
    l2ToL1MessagePasserAbi: "Allowlisted OP L2-to-L1 message passer ABI.",
  };
  return `/** ${descriptions[exportName]} */`;
}
